# Codecov settings
# After modifying this file, it might be worth to validate it with:
# `curl --data-binary @.codecov.yml https://codecov.io/validate`

# which branch to monitor and whether wait for ci success
codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

# define the colour bar limits here
coverage:
  precision: 2
  round: down
  range: "75...100"

  # diff type
  status:
    project:
      default:
        # commits below this threshold will be marked as failed
        target: '100%'
    patch:
      default:
        # basic
        target: '100%'

# turn off comments to pull requests
comment: off
